version: '3.9'

services:
  coweureka:
    container_name: ${APPLICATION_NAME}
    image: ${REPOSITORY}/${APPLICATION_NAME}:${SPRING_PROFILES_ACTIVE}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    env_file:
      - .env
    networks:
      - cownetwork

networks:
  cownetwork:
    external: true
    driver: bridge
