version: '3.9'

services:
  coweureka:
    container_name: eureka
    image: eureka
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8761:8761
    networks:
      - cownetwork

networks:
  cownetwork:
    external: true
    driver: bridge
