spring:
  application:
    name: ${APPLICATION_NAME}
server:
  port: ${INTERNAL_PORT}
eureka:
  instance:
    hostname: ${HOST_NAME}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${HOST_NAME}:${EXTERNAL_PORT}/eureka/